### ISSUE TITLE
Some questions wioth FLOPs calculation in ViT

### ISSUE THREAD

**Issue by Liuyang829** [blackfeather-wang/Dynamic-Vision-Transformer#3]
Thanks for your great work. I am interested in the FLOPs reported in your paper like `table 1 ` `table 4`. I am wondering if you can release the code of FLOPs calcuation for ViT. Thank you!

**Comment by blackfeather-wang** [comment]
Thank you for your attention to our work! We use the fvcore toolkit to obtain the FLOPs. Please refer to https://github.com/facebookresearch/fvcore/blob/main/docs/flop_count.md for details.
