### ISSUE TITLE
Could you give us some example checkpoint of ImageNet 2014 or anything else?

### ISSUE THREAD

**Issue by xiyiyia** [blackfeather-wang/Dynamic-Vision-Transformer#4]
I try to evaluate your model on my machine. Unfortunately, I find you don't give us any checkpoint in any dataset.  I don't have enough machines to train a new model at ImageNet. Your work is perfect, and It would be a pity if I couldn't run your model. Just one checkpoint file I need! Any dataset is fine! Please. @blackfeather-wang @guanfuchen

Thank you

**Comment by blackfeather-wang** [comment]
![image](https://user-images.githubusercontent.com/39077443/140631909-b8902816-caa4-4684-bfaf-a9fea2cad846.png)
