### ISSUE TITLE
About the implementation of upsampling in relation_reuse

### ISSUE THREAD

**Issue by larenzhang** [blackfeather-wang/Dynamic-Vision-Transformer#7]
The main concern for me is that what is the necessity to split relation_temp as:
```
  split_index = int(relation_temp.size(0) / 2)
  relation_temp = torch.cat(
      (
          self.relation_reuse_upsample(relation_temp[:split_index * 1]),
          self.relation_reuse_upsample(relation_temp[split_index * 1:]),
      ), 0
  )
```
It is more straight to implement the upsample like this:

```
  relation_temp =  self.relation_reuse_upsample(relation_temp)
```
Could you please explain the difference between the above two implementations?

**Comment by blackfeather-wang** [comment]
Thanks for your attention to our work~
In essence, the two implementations are equivalent. However, the second implementation produces feature maps that are too large to be supported by the operations of CUDA.
